export const imageList: string[] = [
  require('../../../source/A_ (2).jpg'),
  require('../../../source/a_.jpg'),
  require('../../../source/b_ (2).jpg'),
  require('../../../source/B_.jpg'),
  require('../../../source/c_.jpg'),
  require('../../../source/d_ (2).jpg'),
  require('../../../source/D_.jpg'),
  require('../../../source/e_.jpg'),
  require('../../../source/F_.jpg'),
  require('../../../source/g_.jpg'),
  require('../../../source/h_ (2).jpg'),
  require('../../../source/H_.jpg'),
  require('../../../source/J_.jpg'),
  require('../../../source/k_.jpg'),
  require('../../../source/m_ (2).jpg'),
  require('../../../source/M_.jpg'),
  require('../../../source/n_.jpg'),
  require('../../../source/o_ (2).jpg'),
  require('../../../source/O_.jpg'),
  require('../../../source/p_ (2).jpg'),
  require('../../../source/P_.jpg'),
  require('../../../source/q_ (2).jpg'),
  require('../../../source/Q_.jpg'),
  require('../../../source/r_.jpg'),
  require('../../../source/s_.jpg'),
  require('../../../source/t_.jpg'),
  require('../../../source/u_ (2).jpg'),
  require('../../../source/U_.jpg'),
  require('../../../source/v_.jpg'),
  require('../../../source/W_.jpg'),
  require('../../../source/x_ (2).jpg'),
  require('../../../source/X_.jpg'),
  require('../../../source/y_ (2).jpg'),
  require('../../../source/Y_.jpg'),
  require('../../../source/z_ (2).jpg'),
  require('../../../source/Z_.jpg'),
];
